parameters:
#    ktq_key_media.example.class: KTQ\Bundle\KeyMediaBundle\Example

services:
#    ktq_key_media.example:
#        class: %ktq_key_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
