parameters:
    ezpublish.fieldType.keymedia.class: KTQ\Bundle\KeyMediaBundle\FieldType\KeyMedia\Type
    ezpublish.fieldType.keymedia.converter.class: KTQ\Bundle\KeyMediaBundle\FieldType\KeyMedia\Converter

services:
    ezpublish.fieldType.keymedia:
        class: %ezpublish.fieldType.keymedia.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: keymedia}

    ezpublish.fieldType.keymedia.converter:
        class: %ezpublish.fieldType.keymedia.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: keymedia, lazy: true, callback: '::create'}
